// 1. Hardcoded Local Asset Catalog
const itemCatalog = [
  {
    name: "75-inch TV Box",
    desc: "Typical 75\" TV packaging. Perfect for verifying rear-seat or trunk clearance.",
    w: 1.70, // meters
    h: 1.00,
    d: 0.20
  },
  {
    name: "Standard 3-Seater Sofa",
    desc: "Standard living room couch. Check elevator capacity or stairwells before delivery.",
    w: 2.20,
    h: 0.90,
    d: 0.90
  },
  {
    name: "French-Door Refrigerator",
    desc: "Double-door refrigerator. Essential for checking tight hallways or door frames.",
    w: 0.90,
    h: 1.80,
    d: 0.90
  }
];

let currentItem = { ...itemCatalog[0] };
let isPlaced = false;
let isColliding = false;
let hitPointsHistory = []; // Points in 3D representing physical surfaces (point cloud collision detection)
let lastUIInteractionTime = 0; // Cooldown timer to prevent WebXR select events when tapping HTML buttons

// Track pointerdowns on UI to filter out WebXR taps
window.addEventListener('pointerdown', (e) => {
  // Check if click is on interactive UI elements or inside the bottom sheet / header
  const isUI = e.target.closest('.interactive') || e.target.closest('#bottom-sheet') || e.target.closest('header');
  if (isUI) {
    lastUIInteractionTime = Date.now();
  }
});

// UI Tab Switches
function switchTab(tab) {
  document.querySelectorAll('.tab-btn').forEach(btn => btn.classList.remove('active'));
  document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));

  document.getElementById(`tab-${tab}`).classList.add('active');
  document.getElementById(`content-${tab}`).classList.add('active');
}

// Select Catalog Item
function selectItem(index) {
  document.querySelectorAll('.product-card').forEach(c => c.classList.remove('selected'));
  document.getElementById(`prod-${index}`).classList.add('selected');

  currentItem = { ...itemCatalog[index] };
  updateHUD();
  updateBoxDimensions();
  showToast(`Selected: ${currentItem.name}`);
}

// Apply Custom Manual Input Dimensions
function applyCustomDims() {
  const w = parseFloat(document.getElementById('input-w').value) || 1.0;
  const h = parseFloat(document.getElementById('input-h').value) || 1.0;
  const d = parseFloat(document.getElementById('input-d').value) || 1.0;

  currentItem = {
    name: "Custom Bounding Box",
    desc: "Custom dimensioned volume generated by manual inputs.",
    w: Math.max(0.05, w),
    h: Math.max(0.05, h),
    d: Math.max(0.05, d)
  };

  updateHUD();
  updateBoxDimensions();
  showToast(`Generated: ${w.toFixed(2)}m x ${h.toFixed(2)}m x ${d.toFixed(2)}m`);
}

// Update HUD text values
function updateHUD() {
  document.getElementById('hud-item-name').innerText = currentItem.name;

  const wInches = currentItem.w * 39.3701;
  const hInches = currentItem.h * 39.3701;
  const dInches = currentItem.d * 39.3701;
  
  const dimsImperial = `${wInches.toFixed(0)}" x ${hInches.toFixed(0)}" x ${dInches.toFixed(0)}"`;
  const dimsMetric = `${currentItem.w.toFixed(2)}m x ${currentItem.h.toFixed(2)}m x ${currentItem.d.toFixed(2)}m`;
  
  document.getElementById('hud-item-dims').innerText = `${dimsImperial}  |  ${dimsMetric}`;
}

// Dynamic scale updating for the A-Frame box entity
function updateBoxDimensions() {
  const boxEntity = document.getElementById('bounding-box');
  const mesh = document.getElementById('box-mesh');

  if (boxEntity && mesh) {
    // Adjust the scale of the base box entity container (A-Frame default box is 1m x 1m x 1m)
    boxEntity.setAttribute('scale', `${currentItem.w} ${currentItem.h} ${currentItem.d}`);
    
    // Compensate the vertical center position of the cube mesh since A-Frame pivots at center.
    mesh.setAttribute('position', '0 0.5 0');
  }
}

// Reset session parameters
function resetARSession() {
  isPlaced = false;
  const boxEntity = document.getElementById('bounding-box');
  if (boxEntity) boxEntity.setAttribute('visible', 'false');

  const reticle = document.getElementById('placement-reticle');
  if (reticle) reticle.setAttribute('visible', 'false');

  isColliding = false;
  hitPointsHistory = [];
  updateStatusBadge('ready', 'Scanning Floor');
  showToast("Session Reset. Scan floor to re-place.");
}

// Show temporary notification toast on HUD
function showToast(message) {
  const toast = document.getElementById('status-toast');
  const text = document.getElementById('toast-text');
  text.innerText = message;
  toast.style.opacity = '1';
  setTimeout(() => {
    toast.style.opacity = '0';
  }, 2500);
}

// Update the visual status dot in the header bar
function updateStatusBadge(state, label) {
  const dot = document.getElementById('ar-status-dot');
  const text = document.getElementById('ar-status-text');
  
  if (dot && text) {
    dot.className = 'status-dot';
    dot.classList.add(state);
    text.innerText = label;
  }
}

// 2. Custom A-Frame Component for WebXR Hit Test
AFRAME.registerComponent('ar-hit-test-listener', {
  init: function () {
    this.xrHitTestSource = null;
    this.viewerSpace = null;
    this.reticleEl = document.getElementById('placement-reticle');
    this.boxEl = document.getElementById('bounding-box');
    
    this.sceneEl.addEventListener('enter-vr', () => {
      if (!this.sceneEl.is('ar-mode')) return;

      showToast("Move phone slowly side-to-side to detect floor");
      updateStatusBadge('scanning', 'Scanning Floor');

      const session = this.sceneEl.xrSession;
      
      // Request viewer space and setup WebXR hit testing
      session.requestReferenceSpace('viewer').then(referenceSpace => {
        this.viewerSpace = referenceSpace;
        session.requestHitTestSource({ space: this.viewerSpace }).then(source => {
          this.xrHitTestSource = source;
        });
      });

      session.addEventListener('select', (e) => {
        // Cooldown check: if they tapped a UI button, do NOT place/move the box
        if (Date.now() - lastUIInteractionTime < 350) {
          console.log("Ignored XR Select: UI interaction detected.");
          return;
        }

        // When user taps on screen, place the box at the current reticle position
        if (this.reticleEl.getAttribute('visible') === 'true') {
          const position = this.reticleEl.getAttribute('position');
          const rotation = this.reticleEl.getAttribute('rotation');

          this.boxEl.setAttribute('position', position);
          this.boxEl.setAttribute('rotation', rotation);
          this.boxEl.setAttribute('visible', 'true');
          
          isPlaced = true;
          showToast("Box Anchored! Walk around to check fit.");
          updateStatusBadge('ready', 'Placed');
          
          // Apply dimensions scale immediately
          updateBoxDimensions();
        }
      });
    });

    this.sceneEl.addEventListener('exit-vr', () => {
      this.xrHitTestSource = null;
      this.viewerSpace = null;
      resetARSession();
      document.getElementById('start-overlay').style.display = 'flex';
    });
  },

  tick: function () {
    const frame = this.sceneEl.frame;
    if (!frame || !this.xrHitTestSource) return;

    const refSpace = this.sceneEl.renderer.xr.getReferenceSpace();
    const hitTestResults = frame.getHitTestResults(this.xrHitTestSource);

    if (hitTestResults.length > 0) {
      const hit = hitTestResults[0];
      const pose = hit.getPose(refSpace);

      // Position reticle based on hit matrix
      this.reticleEl.setAttribute('visible', 'true');
      this.reticleEl.setAttribute('position', {
        x: pose.transform.position.x,
        y: pose.transform.position.y,
        z: pose.transform.position.z
      });
      
      if (!isPlaced) {
        updateStatusBadge('ready', 'Tap to Place');
      }

      // Point-Cloud Collision Engine (Wow Factor)
      const point = {
        x: pose.transform.position.x,
        y: pose.transform.position.y,
        z: pose.transform.position.z
      };
      
      // Feed point cloud history
      if (hitPointsHistory.length > 80) hitPointsHistory.shift(); // Cap history to maintain 60 FPS
      hitPointsHistory.push(point);

      if (isPlaced) {
        checkPointOverlap();
      }
    } else {
      if (!isPlaced) {
        this.reticleEl.setAttribute('visible', 'false');
        updateStatusBadge('scanning', 'Scanning floor');
      }
    }
  }
});

// Check if any tracked physical surface points fall inside our virtual bounding box
function checkPointOverlap() {
  const boxEl = document.getElementById('bounding-box');
  const meshEl = document.getElementById('box-mesh');
  if (!boxEl || !meshEl) return;

  const boxObj = boxEl.object3D;
  let overlapDetected = false;

  // Check bounds in LOCAL coordinate space of the bounding box.
  // Since the parent container (boxEl) is scaled to width, height, and depth,
  // the visual box inside it represents exactly a 1x1x1 unit cube centered at Y=0.5.
  // Therefore, the normalized local bounds are always:
  // - X: [-0.5, 0.5]
  // - Y: [0.05, 1.0] (with a 5cm bottom floor padding)
  // - Z: [-0.5, 0.5]
  // This solves the bug where collision was scaled by dimensions squared!
  for (let i = 0; i < hitPointsHistory.length; i++) {
    const pt = hitPointsHistory[i];
    
    // Convert world hit point into local space of the placed bounding box
    const localPt = new THREE.Vector3(pt.x, pt.y, pt.z);
    boxObj.worldToLocal(localPt);

    const insideX = Math.abs(localPt.x) <= 0.5;
    const insideY = localPt.y > 0.05 && localPt.y <= 1.0;
    const insideZ = Math.abs(localPt.z) <= 0.5;

    if (insideX && insideY && insideZ) {
      overlapDetected = true;
      break;
    }
  }

  const prevColliding = isColliding;
  isColliding = overlapDetected;

  if (isColliding) {
    meshEl.setAttribute('material', 'color', '#f43f5e'); // Red clipping color
    updateStatusBadge('clipping', '⚠️ Collision');
    if (prevColliding !== isColliding) {
      showToast("Collision detected! Box does not fit.");
      if (navigator.vibrate) navigator.vibrate(80);
    }
  } else {
    meshEl.setAttribute('material', 'color', '#10b981'); // Emerald Green safe color
    updateStatusBadge('ready', 'Placed & Fit');
  }
}

// Attach listener component to the scene
document.querySelector('a-scene').setAttribute('ar-hit-test-listener', '');

// WebAR Start Trigger
document.getElementById('start-ar-btn').addEventListener('click', () => {
  const scene = document.querySelector('a-scene');
  scene.enterVR(); // A-Frame enterVR requests AR mode on mobile
  document.getElementById('start-overlay').style.display = 'none';
  updateHUD();
});
